apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: node-disk-auto
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  cachingMode: ReadWrite
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
